# Generated by Django 5.0.6 on 2024-05-11 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_detailspage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailspage',
            name='user',
        ),
    ]
