# Generated by Django 5.0.6 on 2024-05-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_remove_detailspage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailspage',
            name='details_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
