# Generated by Django 5.0.6 on 2024-05-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_detailspage_details_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailspage',
            name='details_id',
            field=models.IntegerField(null=True),
        ),
    ]
